/*
 * ECARX Technology Limited is the owner of the copyright and the trade secret of this software.
 * Without permission, no one has the right to obtain, disclose or use this software in any way.
 */
package ecarx.carext.rvdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.RequiresPermission;

import ecarx.carext.base.BaseAPI;
import ecarx.carext.base.FunctionStatus;
import ecarx.carext.base.Permissions;
import ecarx.carext.base.exception.UnimplementedException;

/**
 * RVDC（Remote Vehicle Data Collection）function is to upload the data generated by the vehicle to the server.
 *
 * @since 1
 */
public interface IRVDC extends BaseAPI {

    /**
     * Get current function status.
     *
     * @since 1
     */
    @NonNull
    @RequiresPermission(Permissions.READ_RVDC)
    default FunctionStatus getFunctionStatus() {
        throw new UnimplementedException();
    }

    /**
     * Get current switch status.
     *
     * @since 1
     */
    @RequiresPermission(Permissions.READ_RVDC)
    @NonNull
    default SwitchStatus getSwitchStatus() {
        throw new UnimplementedException();
    }

    /**
     * Set all switch status together.
     *
     * @return whether this call was successful. Whether it is finally successful or not
     * will be notified later through the callback {@link ISwitchListener#onStatusChanged(SwitchStatus)}.
     * @since 1
     */
    @RequiresPermission(Permissions.WRITE_RVDC)
    default boolean setSwitchStatus(@NonNull SwitchStatus status) {
        throw new UnimplementedException();
    }

    /**
     * Register a callback to be invoked when the switch is changed.
     *
     * @param listener The callback that will run.
     * @since 1
     */
    @RequiresPermission(Permissions.READ_RVDC)
    default void registerSwitchListener(@NonNull ISwitchListener listener) {
        throw new UnimplementedException();
    }

    /**
     * Stop receiving switch updates.
     *
     * @since 1
     */
    @RequiresPermission(Permissions.READ_RVDC)
    default void unregisterSwitchListener(@NonNull ISwitchListener listener) {
        throw new UnimplementedException();
    }

    /**
     * Register a callback to be invoked when a message received from the server.
     *
     * @param listener The callback that will run.
     * @since 1
     */
    @RequiresPermission(Permissions.READ_RVDC)
    default void registerServerListener(@NonNull IServerListener listener) {
        throw new UnimplementedException();
    }

    /**
     * Stop receiving server message.
     *
     * @since 1
     */
    @RequiresPermission(Permissions.READ_RVDC)
    default void unregisterServerListener(@NonNull IServerListener listener) {
        throw new UnimplementedException();
    }

    /**
     * The switch status.
     *
     * @since 1
     */
    class SwitchStatus {
        /**
         * Whether the RVDC switch status on or not.
         *
         * @since 1
         */
        public boolean rvdcOn;
        /**
         * Whether the data collection switch status on or not.
         *
         * @since 1
         */
        public boolean dataCollectionOn;
        /**
         * Whether the remote diagnostics switch status on or not.
         *
         * @since 1
         */
        public boolean remoteDiagnosticsOn;
    }

    /**
     * The notification from Server.
     *
     * @since 1
     */
    class ServerNotification {
        /**
         * The timestamp from server.
         *
         * @since 1
         */
        public long timestamp;
        /**
         * The status from server, for example "FORCED-SYNC-LOG".
         *
         * @since 1
         */
        @NonNull
        public String newStatus;
        /**
         * The reason from server, for example "SYSTEM".
         *
         * @since 1
         */
        @Nullable
        public String reason;
    }

    /**
     * Interface definition for a callback to be invoked when the switch changed.
     *
     * @since 1
     */
    interface ISwitchListener {
        /**
         * Called when a switch status has changed.
         *
         * @param status the latest switch status.
         * @since 1
         */
        void onStatusChanged(@NonNull SwitchStatus status);
    }

    /**
     * Interface definition for a callback to be invoked when a message received from the server.
     *
     * @since 1
     */
    interface IServerListener {
        /**
         * Called when a notification received.
         *
         * @param notification the notification from the server.
         * @since 1
         */
        void onNotificationReceived(@NonNull ServerNotification notification);
    }

}
